
site_name: Zero-TOTP Docs
theme:
  name: material
  palette:
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    - navigation.path
    - search.suggest
    - search.highlight
    - search.share
    - social
    - content.code.copy
    - content.code.select
    - content.code.annotate
  logo: assets/logo.png
  favicon: assets/favicon.ico
  language: en
  icon:
    repo: fontawesome/brands/github
plugins:
  - privacy
  - search
repo_url: https://github.com/SeaweedbrainCY/zero-totp
repo_name: SeaweedbrainCY/zero-totp
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
copyright: Zero-TOTP documentation released under GPL-3.0 Licence. Zero-TOTP is a project of Nathan Stchepinsky © 2023. All rights reserved.

extra:
  social:
    - icon: fontawesome/brands/github
      links: https://github.com/SeaweedbrainCY/zero-totp
    - icon: fontawesome/brands/docker
      links: https://hub.docker.com/u/seaweedbrain
nav: #https://github.com/squidfunk/mkdocs-material/discussions/4699
  - Home:
    - index.md
  - Self-host:
    - self_host/Setup.md
  - Contributing:
    - contrib/Requirements.md
    - contrib/Setup.md
  - Code documentation:
    - code_doc/api.md
    - code_doc/Cryptography.md

  