name: Deploy Zero-TOTP Documentation
on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'


jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write  
            actions: write
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Generate latest version doc
          working-directory: ./zero-totp-docs/content
          run: |
            current_short_version=$(echo ${{ github.ref_name }} | sed 's/\([0-9]*\.[0-9]*\).*$/\1/') 
            echo "Current short version: $current_short_version"
            cp -r $current_short_version/ latest/
            cp $current_short_version/_index.md _index.md

        - name: Install Hugo
          uses: peaceiris/actions-hugo@v2
          with:
              hugo-version: 'latest'
              extended: true
        
        - name: Build documentation
          working-directory: ./zero-totp-docs
          run: |
            hugo --minify --gc --cleanDestinationDir --destination ../docs

        - name: Add CNAME file
          run: |
            echo "docs.zero-totp.com" > ./docs/CNAME
        
        - name: Push to gh-pages branch
          run: |
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            
            git add .
            git commit -m "Deploy documentation for version ${{ github.ref_name }}"
            git push origin HEAD:gh-pages --force

        
            

    
       