name: Deploy Zero-TOTP Documentation



on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'
        


jobs:
    Docker-Build-and-Push:
        runs-on: ubuntu-latest
        permissions:
            contents: write  
            actions: write
            packages: write
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Update modified fileds with their last modified date 
          run: ./utilities/update_last_modified_date.sh
        
        - name: Extract env variables
          id: vars
          run: |
            echo "REPOSITORY_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV 
            echo "CURRENT_VERSION=$(echo ${{ github.ref_name }} | sed 's/\([0-9]*\.[0-9]*\.[0-9]*\).*/\1/')" >> $GITHUB_ENV
            echo "CURRENT_SHORT_VERSION=$(echo ${{ github.ref_name }} | sed 's/\([0-9]*\.[0-9]*\).*$/\1/')" >> $GITHUB_ENV
            echo "GIT_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV



        - name: Login to GHCR 
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push Docker images
          
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: |
              ghcr.io/${{ env.REPOSITORY_NAME }}:latest
              ghcr.io/${{ env.REPOSITORY_NAME }}:${{ env.CURRENT_VERSION }}
              ghcr.io/${{ env.REPOSITORY_NAME }}:${{ env.CURRENT_SHORT_VERSION }}
            labels: |
              org.opencontainers.image.revision=${{ env.GIT_COMMIT }}
              org.opencontainers.image.created=${{ steps.meta.outputs.created }}
              org.opencontainers.image.version=${{ github.ref_name }}
              org.opencontainers.image.title="Zero-TOTP Documentation" 
              org.opencontainers.image.description="Documentation for Zero-TOTP" 
              org.opencontainers.image.authors="Seaweedbrain github.com/SeaweedbrainCY" 
              org.opencontainers.image.url="https://github.com/seaweedbraincy/zero-totp-docs" 
              org.opencontainers.image.source="https://github.com/seaweedbraincy/zero-totp-docs" 
              org.opencontainers.image.licenses="MIT" 
              org.opencontainers.image.documentation="https://github.com/seaweedbraincy/zero-totp-docs#readme" 
              org.opencontainers.image.vendor="Seaweedbrain" 
              org.opencontainers.image.base.name="caddy:alpine"
        
            

    
       